### ISSUE TITLE
Unable to merge or fast forward between gh-pages and master branches

### ISSUE THREAD

**Issue by david-chambers** [Esri/developer-support#212] opened 2016-03-18 18:52 UTC
I just submitted pull request #210 containing a JS sample with a sample URL to our gh-pages branch.  After the PR was approved I was planning to fast forward or submit another PR between gh-pages and master so my readme sample URL was correct per #61. However it seems that an auto-merge is not possible here #211. Did I do something wrong here or is our master and gh-pages branch out of sync?

**Comment by jgravois** [comment] 2016-03-18 19:13
@phpmaps has pushed 14 commits directly to the `gh-pages` branch with changes that conflict with work that was pushed into `master` since the last time they were syncronized.

**please**, **never** push your work directly to **either** of those two branches.  

all work should be performed in a uniquely named branch and incorporated into `master` after code review through a pull request.  if this is done consistently, there will be no need to PR the same changes into `gh-pages`.  that branch will always be behind and able to be fast forwarded by someone with sufficient privileges (more info [here](https://github.com/Esri/developer-support/issues/61#issuecomment-120494878)).

**Comment by phpmaps** [comment] 2016-03-18 19:36
I apologize in terms of gh_pages I guess I though direct pushes were okay there.  Is the message below mean I should never do this?  LMK

**Comment by david-chambers** [comment] 2016-03-18 19:40
@jgravois Thanks John that's what I had assumed.  How do we go about fixing this? Let me know if there is anything I can do to help.

**Comment by jgravois** [comment] 2016-03-18 19:43
> How do we go about fixing this?

i'm all about learning opportunities, so i'd like to leave it up to any brave souls who haven't already encountered something like this to make a suggestion so we can come to an agreement about the best approach to get everything back in an appropriate state.

**Comment by nohe427** [comment] 2016-03-18 19:49
I was hoping you could just force push the latest and greatest to gh-pages

**Comment by jgravois** [comment] 2016-03-18 19:52
a vote for the nuclear option :boom: 

unless additional measures were taken, this would rewrite history in the `gh-pages` branch and blow away all the unique work thats currently only present there.

**Comment by phpmaps** [comment] 2016-03-18 20:03
I guess I am having a hard time understanding the problem.  I continue to see all the web pages –I  just used the center helper javascript app yesterday.   Also I see all the code, like normal.

Is the problem that people are able to continue to contribute / create branches and merge?

LMK

**Comment by NoashX** [comment] 2016-03-18 20:03
this would nicely fold into the SDK WAM #GitHub Worflows with @jgravois (03/23, 1pm, Building V)

**Comment by goldenlimit** [comment] 2016-03-18 20:06
Previously I messed up my branch locally but the best way to learn is messup stuff and fix it. Welcome @jgravois 's coming

**Comment by jgravois** [comment] 2016-03-18 20:10
> @phpmaps: I guess I am having a hard time understanding the problem.

the problem is that @david-chambers encountered a merge conflict when he attempted to incorporate the last several months of work that was done on `master` because the history of the two branches has diverged.

**Comment by phpmaps** [comment] 2016-03-19 09:31
I see.  In terms of problem solving - what about David fetch from upstream and merge in the new changes.  On a different note David let me know if there is something you need from me -  sounds like I jacked up everyones day up pretty badly.

**Comment by jgravois** [comment] 2016-03-19 11:58
> what about David fetch from upstream and merge in the new changes.

when @david-chambers created PR #212, he was already comparing the correct two upstream branches, but @phpmaps is 100% correct here.  

it is **not** possible to merge a PR using github's online tools when a conflict is detected, but it **is** possible to merge the same work locally by stepping through individual conflicts and resolving them manually.

@nohe427's solution technically *would* work, but force pushing is a bad idea in a scenario like this for two reasons.

1) as I mentioned before, @phpmap's work in `gh-pages` would disappear entirely.
2) it would would be **seriously** problematic that the commit history of the `gh-pages` upstream was rewritten because people are tracking changes to that branch.  most importantly, it'd make pushing new local changes from `master` to upstream `gh-pages` impossible because git would notice the discrepancy in the history.

there are two morals to this story:
1) never create/push commits on shared branches
2) **never ever** `git push --force` on shared branches

**Comment by nohe427** [comment] 2016-03-21 18:02
@david-chambers and I resolved this together.

**Closed by nohe427** 2016-03-21 18:02 UTC

**Comment by david-chambers** [comment] 2016-03-21 18:06
Yep! huge kudos to @nohe427 we followed the command line instructions for resolving the merge conflicts (there were two) in @phpmaps samples and then we were able to auto-merge from GitHub.  Glad we didn't have to :boom: it.
